### ISSUE TITLE
Replace the logo in the header

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/paid-qa#103]
- [x] The same component for off-chain voting and paid QA

file
[logo-horizontal-color.zip](https://github.com/opensquare-network/paid-qa/files/8241168/logo-horizontal-color.zip)

preview
<img width="346" alt="image" src="https://user-images.githubusercontent.com/59445675/158091475-31cf84fb-d0e1-4bc3-b5c7-34ad60f832cf.png">

**Comment by YoshiyukiSakura** [comment]
done in commit a649611
