### ISSUE TITLE
Update icon according to Figma design

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/paid-qa#130]
![image](https://user-images.githubusercontent.com/6297057/159196244-c4186aab-22a4-4818-a161-41f4720c1bf2.png)

**Comment by YoshiyukiSakura** [comment]
<img width="343" alt="image" src="https://user-images.githubusercontent.com/12393771/159444937-e1cdc7df-3e1c-4c30-9511-29c26757f7ed.png">
done
