### ISSUE TITLE
Add Funders info to topic detail header

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/paid-qa#138]
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=4470%3A25283

![image](https://user-images.githubusercontent.com/6297057/159196892-f653c54e-fc73-45d6-ac7d-7d1d535c390a.png)

**Comment by YoshiyukiSakura** [comment]
![image](https://user-images.githubusercontent.com/12393771/160351380-e2979532-9aad-456e-ae3b-c2f60c456a03.png)
By figma, these avatars are slightly overlaid
