### ISSUE TITLE
new promise card layout

### ISSUE THREAD

**Issue by YoshiyukiSakura** [opensquare-network/paid-qa#158]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/12393771/159221392-cdf07366-c07b-4f10-84a2-7ab21a0d08ad.png">
# start a new line to display fund data

**Comment by Popoulosss** [comment]
[figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=6811%3A54818)
