### ISSUE TITLE
Implement Notification page template

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/paid-qa#172]
- [x] Add notification button on top right side

![image](https://user-images.githubusercontent.com/6297057/159626097-2372aca5-16ff-4fd1-8c14-2a2b471fa6b8.png)

- [x] Implement Notification page UI template
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=6978%3A30837

**Comment by Popoulosss** [comment]
[figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=6978%3A30837)

Notifications
- All types of messages

Discussions
- Replied (If replied and mentioned happen to the same message, show replied priority)
- Mentioned (@)
- Topic has been resolved (When a topic is set to be resolved, topic publisher and all the topic answers/replier will receive this message)

Rewards
- Rewarded

preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/159644119-ca649d3b-2175-4e53-9d30-97f1fbf019a0.png">
