### ISSUE TITLE
Implement Notification API

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/paid-qa#173]
- [x] Parse answer to create mention notification
- [x] Save reply notification
- [x] Save fund notification
- [x] Add notification listing api
- [x] Add api to check if there are new notifications

**Comment by Popoulosss** [comment]
[figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=6978%3A30837)

Notifications
- All types of messages
Discussions
- Replied (If replied and mentioned happen to the same message, show replied priority)
- Mentioned (@)
- Topic has been resolved (When a topic is set to be resolved, topic publisher and all the topic answers/replier will receive this message)
Rewards
- Rewarded

preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/159644119-ca649d3b-2175-4e53-9d30-97f1fbf019a0.png">
