### ISSUE TITLE
Show loading toast when submitting remark

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/paid-qa#211]
Because submitting qa a remark and syncing the extrinsic data with the server takes a bit of time, it's helpful to have a floating toast to tell the status, like the polkadot app.

- [x] Design the loading toast (@Popoulosss )
- [x] Implement

https://user-images.githubusercontent.com/6297057/160051636-6c8dc42c-6d57-4d78-b8b2-dab9471f92f2.mp4

**Comment by Popoulosss** [comment]
[figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=8020%3A32063)

file (loading animation)
[loading-pending.svg.zip](https://github.com/opensquare-network/paid-qa/files/8347744/loading-pending.svg.zip)

[example: post a topic](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=8020%3A32324)
