### ISSUE TITLE
Implement scan package to scan the system remarks

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/paid-qa#3]
Implement scan package to scan the paid-qa related system remarks and store the remarks in DB
- [x] Save system remark starts with "osn:q:" witch means it is a OpenSquare collaboration qa remarks.
- [x] Handle batch call that contains a system remark and a transfer in one extrinsic, like the FUND interaction.
- [x] Should support scanning different chains: Polkadot/Kusama/Statemint/Statemine/Karura...
- [x] ~Handle un-finalized blocks~

**Comment by wliyongfeng** [comment]
We don't have to handle unFinalized blocks.
