### ISSUE TITLE
Implement new Promise and Reward stats

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/paid-qa#303]
![image](https://user-images.githubusercontent.com/6297057/161908035-771c6390-0e9f-40a8-95b5-b6a392c0ca0c.png)

- [x] Show the numbers of 100% fulfilled promises / total promises
- [x] Show numbers of rewards

**Comment by Popoulosss** [comment]
- [ ] Add tooltip to description details

[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=8330%3A32673)

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/161916759-1ef007f7-c80f-4746-8472-a05a77403699.png">
