### ISSUE TITLE
Add Profile / Reward tab

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/paid-qa#304]
Add reward tab to profile page, show the fund rewards received by the user

- [x] Deisgn (@Popoulosss )
- [x] Implement

**Comment by Popoulosss** [comment]
Refer to [the notification of funds](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=7911%3A32758)

[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=8633%3A35757)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/161916058-b32730c3-0954-4608-b965-cb91d33eea41.png">
