### ISSUE TITLE
Implement chain node endpoint selector

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/paid-qa#34]
- [x] UI Design (@Popoulosss )
- [x] Implement

**Comment by Popoulosss** [comment]
figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=4693%3A53540

preview
<img width="687" alt="image" src="https://user-images.githubusercontent.com/59445675/156716260-899c2342-3e37-4a88-889f-763a9eee2a76.png">
