### ISSUE TITLE
review ui sub-package atomic

### ISSUE THREAD

**Issue by YoshiyukiSakura** [opensquare-network/paid-qa#344]
## So we have this package to be a UI component library, to be shared in paid-QA, collabration(voting) & the up-coming bounty.
The goal is creating a highly reusable library, which requires nice clean defination, such as atomic, low coupling .

Please review the `packages/ui` sub folder and see if you can find anything against the principle

**Comment by 2nthony** [comment]
Should we add some tools for UI development like [storybook](https://storybook.js.org/)? It should be convenient for UI development.

**Comment by YoshiyukiSakura** [comment]
> Should we add some tools for UI development like [storybook](https://storybook.js.org/)? It should be convenient for UI development.

sounds sweet, its fine to import this as  a document-like, since we have limited bandwidth , its likely we will only take very basic use of this
