### ISSUE TITLE
thinking of `toast`

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/paid-qa#355]
<details><summary>outdate</summary>

`site/src/components/Toast`

`site/src/components/Toast/icons/*.svg` => `ui/lib/imgs/icons/`

</details>

**Comment by 2nthony** [comment]
hard to migrate, because of the `reducer/toastSlice`.

**Comment by 2nthony** [comment]
Maybe we can redesign/rewrite the toast, with no reducers. Just some API like open, destroy, success, etc. inspired by [ant.design notification](https://ant.design/components/notification)

The benefit is easy to use in any place.

---

pseudo code

```js
import toast from '@osn/common-ui/lib/toast'

const instance = toast.open({
  type: 'success',
  message: 'lorem',
})
instance.destroy()

toast.success() // shortcut for type: 'success'
toast.warn()
toast.pending()
```

**Comment by YoshiyukiSakura** [comment]
> Maybe we can redesign/rewrite the toast, **with no reducers**. Just simple APIs like `open`, `destroy`, `success`, etc. inspired by [ant.design notification](https://ant.design/components/notification)
> 
> The benefit is can be easy to use in any place with just `toast.open()`.
> 
> pseudo code
> 
> ```js
> import toast from '@osn/common-ui/lib/toast'
> 
> const instance = toast.open({
>   type: 'success',
>   message: 'lorem',
> })
> instance.destroy()
> 
> toast.success() // shortcut for type: 'success'
> toast.warn()
> toast.pending()
> ```

A question for this, where do we  to put component instances? currently we are putting it into App.js & using redux to pass data.

The pseudo code looks promising

**Comment by 2nthony** [comment]
> A question for this, where do we to put component instances? currently we are putting it into App.js & using redux to pass data.

No need to put the component instance to anywhere, let's check the ant design notification usage

```js
import { Button, notification } from 'antd';

const openNotification = () => {
  notification.open({
    message: 'Notification Title',
    description:
      'This is the content of the notification. This is the content of the notification. This is the content of the notification.',
    onClick: () => {
      console.log('Notification Clicked!');
    },
  });
};

ReactDOM.render(
  <Button type="primary" onClick={openNotification}>
    Open the notification box
  </Button>,
  mountNode,
);
```

It will insert the notification HTML code into `<body>` or somewhere.

**Comment by YoshiyukiSakura** [comment]
> > A question for this, where do we to put component instances? currently we are putting it into App.js & using redux to pass data.
> 
> No need to put the component instance to anywhere, let's check the ant design notification usage
> 
> ```js
> import { Button, notification } from 'antd';
> 
> const openNotification = () => {
>   notification.open({
>     message: 'Notification Title',
>     description:
>       'This is the content of the notification. This is the content of the notification. This is the content of the notification.',
>     onClick: () => {
>       console.log('Notification Clicked!');
>     },
>   });
> };
> 
> ReactDOM.render(
>   <Button type="primary" onClick={openNotification}>
>     Open the notification box
>   </Button>,
>   mountNode,
> );
> ```
> 
> It will insert the notification HTML code into `<body>` or somewhere.

just studied [rc-notification](https://github.com/react-component/notification), it will be good if you can implement the refactor, also plz keep in mind we would like the component `next` compatible
