### ISSUE TITLE
REFACTOR: merge `DiscussionItemList.js` `NotificationList.js` `RewardItemList.js`

### ISSUE THREAD

**Issue by YoshiyukiSakura** [opensquare-network/paid-qa#498]
these tree are basically identical
<img width="655" alt="image" src="https://user-images.githubusercontent.com/12393771/165870517-92651c1d-8a94-46af-98b4-ddc936fd62c8.png">
<img width="646" alt="image" src="https://user-images.githubusercontent.com/12393771/165870526-18b73279-6976-46b8-b530-86874afea310.png">

**Comment by 2nthony** [comment]
close #518 , outdated, design changed
