### ISSUE TITLE
Modify notification page

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/paid-qa#515]
[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=9630%3A49822)

[Notification type](https://opensquare.feishu.cn/sheets/shtcneRIUmwWJDnVDJr1hCTQIUo)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/166911318-04d4aedf-720e-4d2d-aee6-cc210eead04a.png">

**Comment by 2nthony** [comment]
## Notification Item

### props

- type
- title
- user: { network, address }
- date
- content?
- status

**Comment by hyifeng** [comment]
- [ ] Remove auto clear unread on opening notification page
![tMmdULG5Ea](https://user-images.githubusercontent.com/6297057/167540244-91f5aa9a-97f1-462e-b9fc-7044f63f53b4.png)

- [ ] Add read/unread status mark
![5yoYeNLX4F](https://user-images.githubusercontent.com/6297057/167540288-10ae5ddd-4eb9-4dbb-866e-878a39b43f31.png)

- [ ] Use the  notification type name listed in the excel table
![xu6Z9HU5ck](https://user-images.githubusercontent.com/6297057/167540472-61e7abf7-5ac1-4115-8fdb-6ec4deecf1d6.png)

- [ ] The Funded balance should be shown in notification

**Comment by Popoulosss** [comment]
<img width="648" alt="image" src="https://user-images.githubusercontent.com/59445675/167567837-7ab481d9-e1b1-4cbc-aafe-93f19fd6afd7.png">
