### ISSUE TITLE
ui: markdown preview default minHeight `19.25px`

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/paid-qa#543]

**Comment by 2nthony** [comment]
min height unset, it is already greater than `19.25`

<img width="264" alt="image" src="https://user-images.githubusercontent.com/19513289/168226533-f3a60bd6-2a33-4090-9b82-676aed3a48b6.png">

**Comment by YoshiyukiSakura** [comment]
> 

what about an empty content? 

e.g. input `<script></script>` , I guess it will be stripped nothing left

**Comment by 2nthony** [comment]
it would be render as text content

<img width="209" alt="image" src="https://user-images.githubusercontent.com/19513289/168227898-b72fe6bb-5db9-4be2-b3d2-b97fb03f3154.png">
