### ISSUE TITLE
chain icon update

### ISSUE THREAD

**Issue by YoshiyukiSakura** [opensquare-network/paid-qa#562]
![origin_img_v2_3e3e37d1-cf1c-4e6e-81cf-e2dff530ca6g](https://user-images.githubusercontent.com/12393771/168205677-5ddec72b-7155-4103-a59f-ff59399759f9.jpg)
might want to do this to `collaboration` too

**Comment by Popoulosss** [comment]
Files
[icons-chains.zip](https://github.com/opensquare-network/paid-qa/files/8683942/icons-chains.zip)
