### ISSUE TITLE
Remove status filter

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/paid-qa#574]
![6oxC7VsBYS](https://user-images.githubusercontent.com/2264908/168468357-d460e491-1934-4d61-ba5c-4496372a0146.png)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=3659%3A30988)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/168510891-3615f3a5-8ffa-4de3-9485-b539163b5030.png">
