### ISSUE TITLE
WND and OSNT should have different asset background colors?

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/paid-qa#575]
![V2BVuMMg2p](https://user-images.githubusercontent.com/2264908/168468430-57626ae8-8ddd-4098-a658-132ded4f02b0.png)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=9983%3A45102)

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/168530489-93f32d08-49f3-486e-b457-101c8b6d41aa.png">
