### ISSUE TITLE
Resolve modal improvement

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/paid-qa#576]
- [x] Text: 'Are you sure to resolve the topic?'. Currently no credit score is calculated.
- [x] Not show the address element for promises.
![upxu9gGPLb](https://user-images.githubusercontent.com/2264908/168468753-57fdd515-e0ea-462c-a218-96361b9f3559.png)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=6807%3A54606)

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/168516396-d15321ce-d926-4de7-87b5-e0358fc6a803.png">
