### ISSUE TITLE
Append icon enhancement

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/paid-qa#580]
When the append box is open, we can replace the edit icon with a cancel button. @Popoulosss 

![XZOKRARRfS](https://user-images.githubusercontent.com/2264908/168480517-e64d0897-87a8-4eeb-a64a-a9ae7d8d60f7.png)

**Comment by Popoulosss** [comment]
- When the editor box is open, edit icon disable
- Add a cancel button
- When click cancel button, hide editor, edit icon active

[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=4782%3A365133)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/168519246-36864903-5961-400a-8e2a-6e34d24ae948.png">

**Comment by 2nthony** [comment]
https://github.com/opensquare-network/rich-text-editor

when the editor is ready
