### ISSUE TITLE
implement <Header> component reponsive style

### ISSUE THREAD

**Issue by YoshiyukiSakura** [opensquare-network/paid-qa#59]

**Comment by YoshiyukiSakura** [comment]
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=4799%3A369479

**Comment by Popoulosss** [comment]
- [ ] Mobile mode does not support wallet connection for now.

preview
<img width="335" alt="image" src="https://user-images.githubusercontent.com/59445675/157202826-9556e140-bd56-4bdb-bcd4-31df1a34d205.png">

**Comment by Popoulosss** [comment]
- [ ] Connecting wallet is not supported in mobile mode

preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/157224626-16901b5f-3531-4a7d-a6c8-88667eb7193a.png">

**Comment by Popoulosss** [comment]
- [ ] Add product switching menu 
- [ ] Implement to voting

preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/157224882-e534f536-2cca-4dc5-8a00-b7f9617ea7c9.png">

**Comment by wliyongfeng** [comment]
Off-chain voting: Multi-chain assets off-chain voting platform for Polkadot ecosystem
Paid QA: Decentralized paid QA platform
