### ISSUE TITLE
Page crash when opening Profile -> Topics tab

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/paid-qa#620]
![image](https://user-images.githubusercontent.com/6297057/170441358-101a6794-d9a7-43c4-bc00-4cfcf2e5aa86.png)

**Comment by wliyongfeng** [comment]
The problem still exist. See [here](https://paid-qa.on.fleek.co/#/network/westend/address/5Dw5KnvTs96FaRQFez1Su15XMMJ65QAi4F1ugNBaXUBiGbX6).
