### ISSUE TITLE
Topic promises section enhancement

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/paid-qa#642]
- [x] Promises should be replaced with `supports` which not includes the fund from the initial fund when topic created.
- [x] There should be a icon on which when we hover it shows a tooltip: "Additional fund promises besides the original promise from OP"
- [x] The funder should be shown on the support record.

![kZMJoU7LxL](https://user-images.githubusercontent.com/2264908/174444700-7c7afa29-170c-4484-aeda-3dd01254b42b.jpg)

**Comment by Popoulosss** [comment]
[Figma link
](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=4470%3A25283)
Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/174517723-54bc4cb3-f7c0-41e4-bed2-f28b5ce2a5ce.png">

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=4711%3A61711)

- If there is no supporter, show placeholder

Preview
<img width="593" alt="image" src="https://user-images.githubusercontent.com/59445675/174578879-ddf2d938-f9b2-4c38-aabe-8c9b7fb12e9b.png">
