### ISSUE TITLE
Show loading when user first open the home page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/paid-qa#75]
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=4991%3A29299

![GPNzmwjT7W](https://user-images.githubusercontent.com/2264908/157401801-8fd9b62c-b4aa-418f-a771-1760a733b2e0.png)

**Comment by wliyongfeng** [comment]
Some search result:

- https://mui.com/components/skeleton/
- https://skeletonreact.com/
- https://github.com/dvtng/react-loading-skeleton

**Comment by YoshiyukiSakura** [comment]
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/12393771/157585489-7f440182-c4c7-44e6-a077-ca2a714e2da7.png">
